---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.4
  driver_config:
    image: "centos:6.4"
    platform: "centos"
  run_list:

- name: ubuntu-12.04
  driver_config:
    image: "ubuntu:12.04"
    platform: "ubuntu"
  run_list:

suites:
  - name: default
    run_list:
      - recipe[spr_selenium::default]
    attributes:

